In [1]:
import pandas as pd

In [5]:

df2 = pd.read_csv("Enplanement.csv")

In [6]:
df1 = pd.read_csv("Airline_Delay_Cause (1).csv")

In [7]:
df1.head()

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2024,12,MQ,Envoy Air,EVV,"Evansville, IN: Evansville Regional",61.0,9.0,1.52,1.08,...,0.0,5.84,0.0,0.0,732.0,47.0,90.0,19.0,0.0,576.0
1,2024,12,MQ,Envoy Air,EWR,"Newark, NJ: Newark Liberty International",107.0,42.0,6.01,5.89,...,0.0,4.94,0.0,0.0,2531.0,335.0,491.0,1251.0,0.0,454.0
2,2024,12,MQ,Envoy Air,EYW,"Key West, FL: Key West International",169.0,31.0,3.37,0.71,...,0.0,15.48,5.0,3.0,1596.0,143.0,52.0,468.0,0.0,933.0
3,2024,12,MQ,Envoy Air,FAR,"Fargo, ND: Hector International",171.0,35.0,4.64,2.12,...,0.0,12.92,2.0,0.0,2428.0,245.0,184.0,575.0,0.0,1424.0
4,2024,12,MQ,Envoy Air,FSD,"Sioux Falls, SD: Joe Foss Field",69.0,14.0,2.00,2.47,...,0.0,4.83,1.0,0.0,720.0,86.0,154.0,191.0,0.0,289.0

In [8]:
df2.head()

,Rank,RO,ST,Locid,City,Airport Name,S/L,Hub,CY 24 Enplanements,CY 23 Enplanements,% Change
0,1.0,SO,GA,ATL,Atlanta,Hartsfield/Jackson Atlanta International,P,L,"52,511,402","50,950,068",3.06%
1,2.0,SW,TX,DFW,Fort Worth,Dallas-Fort Worth International,P,L,"42,351,316","39,246,212",7.91%
2,3.0,NM,CO,DEN,Denver,Denver International,P,L,"40,012,895","37,863,967",5.68%
3,4.0,GL,IL,ORD,Chicago,Chicago O'Hare International,P,L,"38,575,693","35,843,104",7.62%
4,5.0,WP,CA,LAX,Los Angeles,Los Angeles International,P,L,"37,760,834","40,956,673",-7.80%

In [9]:
df1.isna().sum()

year                    0
month                   0
carrier                 0
carrier_name            0
airport                 0
airport_name            0
arr_flights            16
arr_del15              22
carrier_ct             16
weather_ct             16
nas_ct                 16
security_ct            16
late_aircraft_ct       16
arr_cancelled          16
arr_diverted           16
arr_delay              16
carrier_delay          16
weather_delay          16
nas_delay              16
security_delay         16
late_aircraft_delay    16
dtype: int64

In [12]:
Airline = df1.dropna()

In [13]:
Airline.isna().sum()

year                   0
month                  0
carrier                0
carrier_name           0
airport                0
airport_name           0
arr_flights            0
arr_del15              0
carrier_ct             0
weather_ct             0
nas_ct                 0
security_ct            0
late_aircraft_ct       0
arr_cancelled          0
arr_diverted           0
arr_delay              0
carrier_delay          0
weather_delay          0
nas_delay              0
security_delay         0
late_aircraft_delay    0
dtype: int64

In [17]:
Airline

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2024,12,MQ,Envoy Air,EVV,"Evansville, IN: Evansville Regional",61.0,9.0,1.52,1.08,...,0.00,5.84,0.0,0.0,732.0,47.0,90.0,19.0,0.0,576.0
1,2024,12,MQ,Envoy Air,EWR,"Newark, NJ: Newark Liberty International",107.0,42.0,6.01,5.89,...,0.00,4.94,0.0,0.0,2531.0,335.0,491.0,1251.0,0.0,454.0
2,2024,12,MQ,Envoy Air,EYW,"Key West, FL: Key West International",169.0,31.0,3.37,0.71,...,0.00,15.48,5.0,3.0,1596.0,143.0,52.0,468.0,0.0,933.0
3,2024,12,MQ,Envoy Air,FAR,"Fargo, ND: Hector International",171.0,35.0,4.64,2.12,...,0.00,12.92,2.0,0.0,2428.0,245.0,184.0,575.0,0.0,1424.0
4,2024,12,MQ,Envoy Air,FSD,"Sioux Falls, SD: Joe Foss Field",69.0,14.0,2.00,2.47,...,0.00,4.83,1.0,0.0,720.0,86.0,154.0,191.0,0.0,289.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22604,2024,1,WN,Southwest Airlines,RDU,"Raleigh/Durham, NC: Raleigh-Durham International",685.0,191.0,74.25,1.66,...,1.13,85.13,27.0,4.0,9326.0,3248.0,317.0,1012.0,37.0,4712.0
22605,2024,1,WN,Southwest Airlines,RIC,"Richmond, VA: Richmond International",140.0,35.0,14.17,0.00,...,0.00,17.81,0.0,0.0,1384.0,578.0,0.0,107.0,0.0,699.0
22606,2024,1,WN,Southwest Airlines,RNO,"Reno, NV: Reno/Tahoe International",705.0,134.0,39.02,0.52,...,0.08,80.49,12.0,7.0,6313.0,1464.0,75.0,1012.0,2.0,3760.0
22607,2024,1,WN,Southwest Airlines,ROC,"Rochester, NY: Frederick Douglass Grtr Rochest...",170.0,51.0,23.59,1.11,...,1.00,19.85,4.0,1.0,2520.0,1121.0,130.0,233.0,37.0,999.0
22608,2024,1,WN,Southwest Airlines,RSW,"Fort Myers, FL: Southwest Florida International",700.0,227.0,58.92,1.76,...,0.00,85.15,17.0,1.0,12562.0,3962.0,149.0,3151.0,0.0,5300.0

In [16]:
Airline['month'].unique()

array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1], dtype=int64)

In [20]:
Airline['late_aircraft_delay'].describe()

count     22587.000000
mean       1996.206535
std        7411.037165
min           0.000000
25%          76.000000
50%         357.000000
75%        1240.500000
max      279153.000000
Name: late_aircraft_delay, dtype: float64

In [31]:
Airline_scary = Airline[Airline['late_aircraft_delay'] > 87600]
Airline_scary.count()

year                   18
month                  18
carrier                18
carrier_name           18
airport                18
airport_name           18
arr_flights            18
arr_del15              18
carrier_ct             18
weather_ct             18
nas_ct                 18
security_ct            18
late_aircraft_ct       18
arr_cancelled          18
arr_diverted           18
arr_delay              18
carrier_delay          18
weather_delay          18
nas_delay              18
security_delay         18
late_aircraft_delay    18
dtype: int64

In [32]:
Airline_1 = Airline_scary[Airline_scary['late_aircraft_delay'] > 87600]

In [33]:
Airline

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2024,12,MQ,Envoy Air,EVV,"Evansville, IN: Evansville Regional",61.0,9.0,1.52,1.08,...,0.00,5.84,0.0,0.0,732.0,47.0,90.0,19.0,0.0,576.0
1,2024,12,MQ,Envoy Air,EWR,"Newark, NJ: Newark Liberty International",107.0,42.0,6.01,5.89,...,0.00,4.94,0.0,0.0,2531.0,335.0,491.0,1251.0,0.0,454.0
2,2024,12,MQ,Envoy Air,EYW,"Key West, FL: Key West International",169.0,31.0,3.37,0.71,...,0.00,15.48,5.0,3.0,1596.0,143.0,52.0,468.0,0.0,933.0
3,2024,12,MQ,Envoy Air,FAR,"Fargo, ND: Hector International",171.0,35.0,4.64,2.12,...,0.00,12.92,2.0,0.0,2428.0,245.0,184.0,575.0,0.0,1424.0
4,2024,12,MQ,Envoy Air,FSD,"Sioux Falls, SD: Joe Foss Field",69.0,14.0,2.00,2.47,...,0.00,4.83,1.0,0.0,720.0,86.0,154.0,191.0,0.0,289.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22604,2024,1,WN,Southwest Airlines,RDU,"Raleigh/Durham, NC: Raleigh-Durham International",685.0,191.0,74.25,1.66,...,1.13,85.13,27.0,4.0,9326.0,3248.0,317.0,1012.0,37.0,4712.0
22605,2024,1,WN,Southwest Airlines,RIC,"Richmond, VA: Richmond International",140.0,35.0,14.17,0.00,...,0.00,17.81,0.0,0.0,1384.0,578.0,0.0,107.0,0.0,699.0
22606,2024,1,WN,Southwest Airlines,RNO,"Reno, NV: Reno/Tahoe International",705.0,134.0,39.02,0.52,...,0.08,80.49,12.0,7.0,6313.0,1464.0,75.0,1012.0,2.0,3760.0
22607,2024,1,WN,Southwest Airlines,ROC,"Rochester, NY: Frederick Douglass Grtr Rochest...",170.0,51.0,23.59,1.11,...,1.00,19.85,4.0,1.0,2520.0,1121.0,130.0,233.0,37.0,999.0
22608,2024,1,WN,Southwest Airlines,RSW,"Fort Myers, FL: Southwest Florida International",700.0,227.0,58.92,1.76,...,0.00,85.15,17.0,1.0,12562.0,3962.0,149.0,3151.0,0.0,5300.0

In [37]:
Enplanement =df2.dropna()

In [38]:
Enplanement["CY 24 Enplanements"] = pd.to_numeric(Enplanement["CY 24 Enplanements"].str.replace(",", ""), errors="coerce")
Enplanement["CY 23 Enplanements"] = pd.to_numeric(Enplanement["CY 23 Enplanements"].str.replace(",", ""), errors="coerce")

C:\Users\cmgol\AppData\Local\Temp\ipykernel_34164\4049692982.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Enplanement["CY 24 Enplanements"] = pd.to_numeric(Enplanement["CY 24 Enplanements"].str.replace(",", ""), errors="coerce")
C:\Users\cmgol\AppData\Local\Temp\ipykernel_34164\4049692982.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Enplanement["CY 23 Enplanements"] = pd.to_numeric(Enplanement["CY 23 Enplanements"].str.replace(",", ""), errors="coerce")

In [40]:
Enplanement["% Change"] = pd.to_numeric(Enplanement["% Change"].str.replace("%", ""), errors="coerce")

C:\Users\cmgol\AppData\Local\Temp\ipykernel_34164\2814639662.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Enplanement["% Change"] = pd.to_numeric(Enplanement["% Change"].str.replace("%", ""), errors="coerce")

In [41]:
Enplanement["Rank"] = Enplanement["Rank"].astype(int)

C:\Users\cmgol\AppData\Local\Temp\ipykernel_34164\4068018824.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Enplanement["Rank"] = Enplanement["Rank"].astype(int)

In [42]:
Enplanement

,Rank,RO,ST,Locid,City,Airport Name,S/L,Hub,CY 24 Enplanements,CY 23 Enplanements,% Change
0,1,SO,GA,ATL,Atlanta,Hartsfield/Jackson Atlanta International,P,L,52511402,50950068,3.06
1,2,SW,TX,DFW,Fort Worth,Dallas-Fort Worth International,P,L,42351316,39246212,7.91
2,3,NM,CO,DEN,Denver,Denver International,P,L,40012895,37863967,5.68
3,4,GL,IL,ORD,Chicago,Chicago O'Hare International,P,L,38575693,35843104,7.62
4,5,WP,CA,LAX,Los Angeles,Los Angeles International,P,L,37760834,40956673,-7.80
...,...,...,...,...,...,...,...,...,...,...,...
392,406,NM,UT,VEL,Vernal,Vernal Regional,P,N,10578,13952,-24.18
393,407,SO,FL,FXE,Fort Lauderdale,Fort Lauderdale Exec,P,N,10493,10625,-1.24
394,409,WP,CA,BIH,Bishop,Bishop,P,N,10119,10007,1.12
395,410,AL,AK,GST,Gustavus,Gustavus,P,N,10074,9584,5.11
396,713,GL,OH,YNG,Youngstown,Youngstown/Warren Regional,P,N,523,730,-28.36

In [43]:
Enplanement["Hub"] = Enplanement["Hub"].fillna("Non-hub")

C:\Users\cmgol\AppData\Local\Temp\ipykernel_34164\844562696.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Enplanement["Hub"] = Enplanement["Hub"].fillna("Non-hub")